[variables]
db_domain = "${domain}"
postgres_user = "admin"
postgres_password = "${password:16}"
postgres_db = "dokploy_db"

[config]
[[config.domains]]
serviceName = "postgres-public"
port = 5432
host = "${db_domain}"

[config.env]
POSTGRES_USER = "${postgres_user}"
POSTGRES_PASSWORD = "${postgres_password}"
POSTGRES_DB = "${postgres_db}"
DB_DOMAIN = "${db_domain}"
