[variables]
main_domain = "${domain}"
postgres_user = "admin"
postgres_password = "${password:16}"
postgres_db = "dokploy_db"
anon_role = "web_anon"
db_schema = "public"

[config]
[[config.domains]]
serviceName = "postgres-with-postgrest"
port = 3000
host = "${main_domain}"

[config.env]
POSTGRES_USER = "${postgres_user}"
POSTGRES_PASSWORD = "${postgres_password}"
POSTGRES_DB = "${postgres_db}"
PGRST_DB_SCHEMA = "${db_schema}"
PGRST_DB_ANON_ROLE = "${anon_role}"
