version: "3.8"
services:
  nexode-backend:
    image: lucast1574/nexode-backend:latest
    restart: always
    environment:
      - PORT=4000
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - API_PREFIX=${API_PREFIX}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GRAPHQL_PATH=${GRAPHQL_PATH}
      - GRAPHQL_PLAYGROUND=${GRAPHQL_PLAYGROUND}
      - GRAPHQL_DEBUG=${GRAPHQL_DEBUG}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nexode-net
    depends_on:
      - nexode-mongo

  nexode-mongo:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=nexode
    volumes:
      - nexode-mongo-data:/data/db
    networks:
      - nexode-net

networks:
  nexode-net:
    driver: bridge

volumes:
  nexode-mongo-data:
