[variables]
main_domain = "${domain}"
huly_secret = "${base64:64}"
disable_signup = "false"
smtp_host = ""
smtp_port = "587"
smtp_tls_mode = "secure"
smtp_username = ""
smtp_password = ""
smtp_from = ""
s3_bucket = ""
s3_region = ""
s3_endpoint = ""
s3_access_key = ""
s3_secret_key = ""

[config]
env = [
  "HULY_VERSION=v0.7.426",
  "DOCKER_NAME=huly",
  "HOST_ADDRESS=${main_domain}",
  "SECURE=",
  "HTTP_PORT=80",
  "HTTP_BIND=",
  "TITLE=Huly",
  "DEFAULT_LANGUAGE=en",
  "LAST_NAME_FIRST=true",
  "SECRET=${huly_secret}",
  "DISABLE_SIGNUP=${disable_signup}",
  "SMTP_HOST=${smtp_host}",
  "SMTP_PORT=${smtp_port}",
  "SMTP_TLS_MODE=${smtp_tls_mode}",
  "SMTP_USERNAME=${smtp_username}",
  "SMTP_PASSWORD=${smtp_password}",
  "SMTP_FROM=${smtp_from}",
  "S3_BUCKET=${s3_bucket}",
  "S3_REGION=${s3_region}",
  "S3_ENDPOINT=${s3_endpoint}",
  "S3_ACCESS_KEY=${s3_access_key}",
  "S3_SECRET_KEY=${s3_secret_key}",
]

[[config.domains]]
serviceName = "nginx"
port = 80
host = "${main_domain}"

[[config.mounts]]
filePath = "/volumes/nginx/.huly.nginx"
content = """
server {
    listen 80;
    server_name _;
    client_max_body_size 500M;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://front:8080;
    }

    location /_accounts {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_accounts(/.*)$ $1 break;
        proxy_pass http://account:3000/;
    }

    location /_collaborator {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        rewrite ^/_collaborator(/.*)$ $1 break;
        proxy_pass http://collaborator:3078/;
    }

    location /_transactor {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        rewrite ^/_transactor(/.*)$ $1 break;
        proxy_pass http://transactor:3333/;
    }

    location ~ ^/eyJ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://transactor:3333;
    }

    location /_rekoni {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_rekoni(/.*)$ $1 break;
        proxy_pass http://rekoni:4004/;
    }

    location /_stats {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_stats(/.*)$ $1 break;
        proxy_pass http://stats:4900/;
    }
} 
"""
