[variables]
main_domain = "${domain}"

[config]
mounts = []

[[config.domains]]
serviceName = "roundcube"
port = 80
host = "${main_domain}"

[config.env]
IMAP_SERVER = "tls://mail.example.com"
SMTP_SERVER = "tls://mail.example.com"
ROUNDCUBEMAIL_URL = "https://${main_domain}"

